# Generated by Django 5.2.1 on 2025-05-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
